# Generated by Django 3.0.6 on 2020-06-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='blog_pics')),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('post_blog_title', models.CharField(max_length=100)),
                ('title_category', models.CharField(max_length=100)),
                ('post_blog_summary', models.CharField(max_length=200)),
            ],
        ),
    ]
