# Generated by Django 3.0.6 on 2020-06-17 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_news_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_blog',
            old_name='img',
            new_name='img2',
        ),
    ]
